Consensys/starknet-snap

packages/wallet-ui/src/theme/default.ts
Tiny fix regarding the theme colors to get rid of the linear-gradient.
=> fix: Updated theme colors

packages/starknet-snap/sonar-project.properties, packages/wallet-ui/sonar-project.properties
Secret keys were updated as well in the GitHub configuration.
=> chore: updating sonarcloud project keys

packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/TransactionListItem.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionsList.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.style.ts, packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx, packages/wallet-ui/src/utils/utils.ts
After discussing with Arthur, I changed how we display the decimals in the dapp so that it is more user friendly and "smart".
I also fixed an issue we had with the max button that would sometimes trigger the amount exceeds user balance error.
=> feat: improved decimals display + fix max function in the send modal

.github/workflows/publish-npm-dev.yml
change pipeline directory to root
=> fix: fix publish-dev-to-npm pipeline

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/sendTransaction.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/test/src/sendTransaction.test.ts
- update send transaction dialog layout
- update unit test
=> fix(SF-490): update dialog layout

packages/wallet-ui/src/components/ui/organism/AddTokenModal/AddTokenModal.view.tsx
-  remove html tag from alert dialog
=> fix(SF-494): remove html tag from alert dialog

.github/workflows/deploy-dev.yml, .github/workflows/deploy.yml
- add multiple handle ("," delimiter support ) for invalidate cdn
- update UI s3 destination
=> feat: update deployment cicd

packages/wallet-ui/src/components/ui/organism/Footer/Footer.style.ts, packages/wallet-ui/src/components/ui/organism/Footer/Footer.view.tsx
- add t and c  at footer
- add copy text at footer
ticket: https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-516
=> feat: add t and c at footer

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/index.ts, packages/starknet-snap/src/utils/constants.ts, packages/wallet-ui/src/utils/constants.ts, packages/wallet-ui/src/utils/utils.ts
**Description**
- remove all testnet 2 related code
- remove testnet 2 from snap state, hence no more testnet2 from dropdown
JIRA: https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-520
=> chore: sf-520 remove testnet2

packages/starknet-snap/openrpc/starknet_snap_api_openrpc.json
add `starkNet_estimateFees`, `starkNet_executeTxn`, `starkNet_declareContract`, `starkNet_signTransaction` to json rpc json
=> feat: add open rpc json

README.md
Add intergation guide in read me
=> feat: add intergation guide in read me

packages/starknet-snap/src/utils/constants.ts
add usdc usdt in default token list
=> feat: add usdc usdt

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/index.ts, packages/wallet-ui/src/components/ui/organism/Footer/Footer.view.tsx, yarn.lock
This updates the design for onInstall, onUpdate, and homepage. The only remaining step is to make a util for the dapp URL so it is not hardcoded.
=> feat: Update Snap UIs

packages/wallet-ui/src/App.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx, packages/wallet-ui/src/utils/constants.ts
This PR is to 
- fix the get starknet name request fire earlier than get account, and lead to a connection issue
=> fix: get starknet name issue

.github/workflows/deploy.yml, .github/workflows/publish-npm-dev.yml, packages/starknet-snap/package.json, packages/starknet-snap/snap.manifest.json, yarn.lock
This PR is adding ENV var `SNAP_ENV` into SNAP github action workflow
=> chore: add env val into cicd

packages/starknet-snap/src/utils/constants.ts
This PR is to update the name and symbol of starknet 
name : Starknet Token
symbol: STRK
=> fix: update starknet token name and symbol

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/index.ts, yarn.lock
The PR is to fix the JSON RPC error when the snap new installed from other dapp instead of the default wallet UI
=> fix: snap homepage error when state omit

.github/workflows/deploy.yml, .github/workflows/publish-npm-dev.yml, packages/starknet-snap/snap.config.js, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/test/utils/snapUtils.test.ts, packages/wallet-ui/src/services/useStarkNetSnap.ts
This PR is to fix voyager cors issue by updating the provider to a official voyager beta provider
this PR should  as quick fix to resolve the cors issue ASAP
note: there is a request limit 30K request per day
=> fix: sf 606 fix voyager cors with official provider

packages/starknet-snap/src/index.ts
This PR is to fix snap homepage ui error due to goerli network deprecated
=> fix: snap homepage ui error due to goerli network deprecated

.github/workflows/deploy-dev.yml, .github/workflows/publish-npm-dev.yml
This PR is to remove auto deploy to DEV when main branch commit to avoid when QA needed to test some special branch
=> chore: remove main from deploy dev rules

packages/starknet-snap/test/src/index.test.ts
This PR is to update the lint style to pass the yarn check
=> chore: fix lint style on snap

packages/wallet-ui/src/components/ui/organism/DeployModal/DeployModal.view.tsx, packages/wallet-ui/src/components/ui/organism/UpgradeModel/UpgradeModel.view.tsx
This PR is to update the waiting deploy/upgrade txn complete in wallet UI
Jira: https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-662
=> fix: update message for waiting deploy/upgrade txn complete

.github/workflows/main.yml
This PR is adding Github Merge Queue
=> chore: add merge queue

packages/get-starknet/src/utils/error.ts
This PR is to update get starknet error message for invalid request
=> chore(get-starknet): update get starknet error message for invalid request

packages/wallet-ui/package.json, packages/wallet-ui/src/types/index.ts, yarn.lock
This PR remove the Snap dependency on Wallet UI package
fix: Remove Snap dependency on Wallet UI package
=> fix(UI): remove Snap dependency on Wallet UI package

.github/workflows/deploy.yml, .github/workflows/publish-npm.yml
This PR is to replace VOYAGER env variable by STARKSCAN in CI/CD
=> chore: replace voyager by starkscan api key

packages/get-starknet/src/wallet.ts
This PR is to add deprecated message for the v3.3 get-starknet Starknet Window Object Property
=> fix: add deprecated message in get-starknet

packages/wallet-ui/src/assets/locales/en.json, packages/wallet-ui/src/assets/locales/fr.json, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/TransactionListItem.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/types.ts
This PR is to fix the missing translation from UI that cause by dynamic transaction name from `getTxnName`
=> chore: add missing translation

packages/wallet-ui/src/App.tsx, packages/wallet-ui/src/components/ui/organism/MinMetamaskVersionModal/MinMetamaskVersionModal.style.ts, packages/wallet-ui/src/components/ui/organism/MinMetamaskVersionModal/MinMetamaskVersionModal.view.tsx, packages/wallet-ui/src/components/ui/organism/MinMetamaskVersionModal/index.ts, packages/wallet-ui/src/components/ui/organism/MinVersionModal/MinVersionModal.view.tsx, packages/wallet-ui/src/hooks/useHasMetamask.ts, packages/wallet-ui/src/slices/modalSlice.ts
This PR is to split the the Modal for `Min Metamask Version` from `MinVersionModal`
=> chore: split MM min version modal

packages/get-starknet/webpack.config.local.js
This PR is to add CORS header for local get-starknet env
=> chore: add CORS header for local get-starknet env
