packages/starknet-snap/LICENSE-APACHE, packages/starknet-snap/LICENSE-MIT
Licenses get packaged directly in npm package, fixes some licensing scanning issues for some systems like `socket.dev`
=> chore: adding licenses directly to package

.github/workflows/build-test.yml, .github/workflows/deploy.yml, .github/workflows/publish-npm-dev.yml, packages/wallet-ui/src/services/useStarkNetSnap.ts, yarn.lock
due to yarn 2.0+, yarn version and publish cmd is not support, thus, change yarn to npm for version and publish cmd
Affected file:
- .github/workflows/deploy.yml
- .github/workflows/publish-npm-dev.yml
=> fix: fix deploy pipeline

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/getTransactions.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/test/constants.test.ts, packages/starknet-snap/test/src/getTransactions.test.ts, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/TransactionListItem.style.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/TransactionListItem.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/types.ts
Background:
Breaking changes introduced in Pathfinder 0.7 and RPC 0.4 for statuses read (deprecation of "status" field for "execution_status" + "finality_status") will be taken into account in a new version of the snap -> Consensys will start working on this in parallel of the MM stable launch and will communicate with Starknet team on expected release date (hard deadline is the v0.13 release in October)
Description:
for get status API, change RPC provider from feeder_gateway to infura
for bulk gas est API, change RPC provider from feeder_gateway to infura
return execution_status and finality_status for snap method starkNet_getTransactionStatus and starkNet_getTransactions
Reference:
https://www.notion.so/Starknet-Snap-update-for-Starknet-v0-12-upgrade-7af534eb6c82410ab6977d209b5cd44e?pvs= …
=> feat: sf 511 deprecation of status field for UI

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/addErc20Token.ts, packages/starknet-snap/src/createAccount.ts, packages/starknet-snap/src/estimateFee.ts, packages/starknet-snap/src/recoverAccounts.ts, packages/starknet-snap/src/signMessage.ts, packages/starknet-snap/src/types/snapState.ts, packages/starknet-snap/src/utils/constants.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/test/constants.test.ts, packages/starknet-snap/test/src/createAccount.test.ts, packages/starknet-snap/test/src/estimateFee.test.ts, packages/starknet-snap/test/src/recoverAccounts.test.ts, packages/starknet-snap/test/src/sendTransaction.test.ts, packages/starknet-snap/test/utils/starknetUtils.test.ts
- update recover account to return correct address 
- add upgradeRequired into acc object
- add update determination by using `isUpgradeRequired` method
- add determination of cario 1 or cario 0
- throw error if error of callcontract is not `contract not found`
- update create account to use isAccountAddressDeployed method
- update est gas fee to use new accountClassHash
- fix test case
=> feat: change account contract to cairo 1

packages/starknet-snap/test/src/createAccount.test.ts, packages/starknet-snap/test/src/estimateFee.test.ts
Get Balance mock is missing in estimateFee and createAccount method
hence, the request will be send to internet during the unit test and cause 1.5 second latency
the fix is to mock the get balance to make skip the actual call
=> fix: add mock to unit test on estimateFee and createAccount

packages/starknet-snap/index.html
refactor Snap demo html to:
1. easier to add new method by adding new method into a array `formWithSubmit` with form id and handler
```
const formWithSubmit = [
...,
{
id: 'new form',
method: methodHandler,
},
]
```
2. reusable method `callSnap` to interacting with snap
```
//e.g
await callSnap(
'starkNet_signMessage', //snap method name
{ typedDataMessage, signerAddress }, //params
);
```
=> feat: update snap demo html

packages/starknet-snap/src/addErc20Token.ts, packages/starknet-snap/src/createAccount.ts, packages/starknet-snap/src/sendTransaction.ts, packages/starknet-snap/src/signMessage.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/test/src/signMessage.test.ts
simplify dialog text render method by adding reusable method `addDialogTxt` and apply the method to methods that to render dialog txt, e.g `getTxnSnapTxt`
rename method `getSigningSnapTxt` to `getSendTxnText` to avoid confusion
=> feat: simplify dialog text render method

packages/wallet-ui/src/slices/walletSlice.ts
**Description**:
The snap not able to reconnect to the wallet ui after disconnected 
Issue: https://consensyssoftware.atlassian.net/browse/SF-573
**Resolution**:
the root cause is the "ethereum" provider reset after disconnected, and there is no operation to re-init the provider, hence the screen freeze when try to use the provider to request snap connect
to address the problem, not to reset the provider even disconnect, as the provider is not part of the snap wallet, it is the permanent connection with metamask 
**Limitation**:
a user disconnect the app and remove/disable the metamask, and try to click the re-connect button will not take effect
=> fix: fix wallet cant connect after disconnect

packages/starknet-snap/src/switchNetwork.ts, packages/starknet-snap/src/types/snapApi.ts, packages/starknet-snap/test/src/switchNetwork.test.ts, packages/wallet-ui/src/components/ui/organism/Menu/Menu.view.tsx, packages/wallet-ui/src/services/useStarkNetSnap.ts
- [UI] add `starkNet_getCurrentNetwork` and `starkNet_switchNetwork` methods in `useStarkNetSnap` hook
- [UI] get the current network by from wallet state when `initSnap` trigger and assign to `activeNetwork` reducer
- [UI] implement `starkNet_switchNetwork` in switch network operation, it only switch the UI network when the methods trigger successfully 
- [SNAP] implement `enableAutherize` to support skip user confirm dialog for `starkNet_switchNetwork`
=> feat: implement network switch in UI

packages/starknet-snap/src/estimateFees.ts, packages/starknet-snap/src/recoverAccounts.ts, packages/starknet-snap/src/utils/constants.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/test/constants.test.ts, packages/starknet-snap/test/src/estimateFee.test.ts, packages/starknet-snap/test/src/estimateFees.test.ts, packages/starknet-snap/test/src/extractPrivateKey.test.ts, packages/starknet-snap/test/src/extractPublicKey.test.ts, packages/starknet-snap/test/src/recoverAccounts.test.ts, packages/starknet-snap/test/src/sendTransaction.test.ts, packages/starknet-snap/test/src/signMessage.test.ts, packages/starknet-snap/test/src/verifySignedMessage.test.ts, packages/starknet-snap/test/utils/starknetUtils.test.ts
- simplify `recoverAccount` to avoid duplicate called on `isUpgradeRequired`
- chore hardcode cairo version 1 to constant `CAIRO_VERSION `
- fix `findAddressIndex` should return address if the address match either cairo0 or cairo{N}
- fix `getCorrectContractAddress`, use getVersion instead of getOwner to determine account has deployed or not
- chore `getCorrectContractAddress` to return upgrade required attribute
=> feat: sf 549 update all method to support upgraded address

packages/starknet-snap/snap.manifest.json, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx
This PR is enable back the starknet ID due to using latest SNAP api framework
when no starknet id found, the error will no longer break the snap
=> chore: enable starknet id

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/index.ts, yarn.lock
This PR is to fix the incorrect balance showing from the Metamask SNAP homepage screen
=> fix: get correct balance on snap homepage

packages/starknet-snap/src/signDeclareTransaction.ts, packages/starknet-snap/src/signDeployAccountTransaction.ts, packages/starknet-snap/src/signMessage.ts, packages/starknet-snap/src/signTransaction.ts, packages/starknet-snap/src/switchNetwork.ts, packages/starknet-snap/src/types/snapApi.ts, packages/starknet-snap/test/src/signDeclareTransaction.test.ts, packages/starknet-snap/test/src/signDeployAccountTransaction.test.ts, packages/starknet-snap/test/src/signMessage.test.ts, packages/starknet-snap/test/src/signTransaction.test.ts, packages/starknet-snap/test/src/switchNetwork.test.ts
This PR is to fix the typo in SNAP, including
`enableAutherize` to `enableAuthorize`
`Autherizeable` to `Authorizable`
=> fix: typo for enable autherize

packages/starknet-snap/src/index.ts
This PR is a temp fix for replacing `address` field by `text` field  due to metamask latest version bug.
=> fix: address field error

packages/get-starknet/src/snap.ts
This PR is to fix an issue whenever a request fire to snap, if any value in params is undefined, e.g
```json
{
data : 1,
somekey: undefined
}
```
it will block by metamask superstruct due to firefox convert undefined to an object
this fix is to remove any incoming undefined params before send to snap
=> fix: get-starknet execute txn not working in firefox

packages/starknet-snap/snap.manifest.json, packages/starknet-snap/src/createAccount.ts, packages/starknet-snap/src/sendTransaction.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/test/src/createAccount.test.ts, packages/starknet-snap/test/src/sendTransaction.test.ts, packages/starknet-snap/test/utils/snapUtils.test.ts, packages/starknet-snap/test/utils/starknetUtils.test.ts, yarn.lock
Due to a issue of [SF-636](https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-636)
This PR is to add waitForTransaction on create account rpc method, to allow the snap to wait for the deploy txn successfully land on L2
[SF-636]: https://consensyssoftware.atlassian.net/browse/SF-636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add waiting mode for create account

.github/workflows/deploy.yml
This PR is to fix a bug in the CICD pipeline when processiong “Deployments" workflow
if the same commit point deploy twice in different env, the latter deploy code will reuse the build from prev build from a cache, and lead to incorrect deployment
solution:
adding the cache with key `commit sha + '-' + env`
jira: https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-651
=> fix: add cache key for different env in CICD

packages/starknet-snap/src/createAccount.ts, packages/starknet-snap/test/src/createAccount.test.ts, yarn.lock
This PR is to fix, the get balance call is fail during create account 
the solution is to remove the get balance call, as it doesnt needed , starknet.js will auto estimate for user, 
Note: it may break tx v3, but we should fix it in tx v3, but not this PR
jira:
https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-650
=> fix: remove get balance from createAccount

package.json, packages/starknet-snap/package.json, packages/starknet-snap/src/index.ts, packages/starknet-snap/test/src/index.test.ts, packages/wallet-ui/src/components/ui/organism/DeployModal/DeployModal.view.tsx
This PR is to 
- fix the issue, when an account discover (recoverAccount api) return an address that is not sync with the snap home page
- fixing the UI to display the address that is marked as required deploy
- lower the test coverage to bypass the CI
jira: 
https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-657
fixed screen capture
=> fix: sync the account from snap homepage with recover

packages/wallet-ui/src/hooks/useHasMetamask.ts, yarn.lock
This PR includes updates to the MetaMask detection logic and the removal of legacy MetaMask Flask support:
1. **Updates to `useHasMetamask.ts`:**
- Added import for `EIP6963ProviderDetail` and `eip6963RequestProvider` from `@metamask/providers`.
- Updated the `useEffect` hook to use the new detection method (`eip6963RequestProvider`) for checking if MetaMask is installed.
- Modified `detectMetamask` to return a `Promise<EIP6963ProviderDetail | null>` using the new detection method.
- Added a fallback to the legacy detection method (`detectMetamaskLegacy`) to ensure compatibility.
- Replaced the previous `detectMetamask` function with `detectMetamaskLegacy` to handle the legacy detection process.
- Cleaned up the `getProvider` function by removing commented lines and refining provider …
=> fix: eip 6963 detection on wallet-ui

packages/starknet-snap/src/utils/error.test.ts, packages/starknet-snap/src/utils/error.ts
This PR is to add an error utils to check if the error is an Snap Error
This PR can be combine to use with this  PR https://github.com/Consensys/starknet-snap/pull/305 
When validate request is throwing an Snap Error, and we should not hide the validation error by checking if the error is an snap error or not 
possible use case
```
try {
validateRequest(params, struct)
} catch (error) {
if (isSnapRpcError(error) {
throw error
}
throw new SnapError('masked error message')
}
```
=> refactor: add error utils

packages/starknet-snap/src/utils/snap.test.ts, packages/starknet-snap/src/utils/snap.ts
This PR is to add a snap utils tool to group the snap necessary function (not apply to the code base yet)
it constains
- getBip44Deriver : A method to request snap_getBip44Entropy
- confirmDialog: A method to request confirm dialog
- getStateData: A method to retrieves the current state data
- setStateData: A method to sets the current state data to the specified data.
=> refactor: add snap utils tool

packages/starknet-snap/src/utils/__mocks__/snap.ts
This PR is to add mocking for snap helper `./utils/snap.ts` for future unit test purpose
=> refactor: add mock for snap helper

packages/starknet-snap/src/declareContract.ts, packages/starknet-snap/src/estimateFee.ts, packages/starknet-snap/src/executeTxn.ts, packages/starknet-snap/src/extractPrivateKey.ts, packages/starknet-snap/src/extractPublicKey.ts, packages/starknet-snap/src/signDeclareTransaction.ts, packages/starknet-snap/src/signDeployAccountTransaction.ts, packages/starknet-snap/src/signMessage.ts, packages/starknet-snap/src/signTransaction.ts, packages/starknet-snap/src/utils/__mocks__/snap.ts, packages/starknet-snap/src/utils/exceptions.ts, packages/starknet-snap/src/utils/snap.test.ts, packages/starknet-snap/src/utils/snap.ts, packages/starknet-snap/src/utils/snapUtils.test.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/src/verifySignedMessage.ts, packages/starknet-snap/test/src/declareContract.test.ts, packages/starknet-snap/test/src/executeTxn.test.ts, packages/starknet-snap/test/src/signDeclareTransaction.test.ts, packages/starknet-snap/test/src/signDeployAccountTransaction.test.ts, packages/starknet-snap/test/src/signMessage.test.ts, packages/starknet-snap/test/src/signTransaction.test.ts, packages/starknet-snap/test/src/verifySignedMessage.test.ts
This PR is to add new method `verifyIfAccountNeedUpgradeOrDeploy`  in snapUtils to group the logic of
- show update/deploy alert dialog (optional)
- check if the account needed to upgrade or deploy
- throw upgrade or deploy required error
it also update the `showDeployRequestModal ` and `showUpgradeRequestModal ` to use the alertDialog utils from `snap`
it also remove some of the test case that depends on the removed method `showAccountRequireUpgradeOrDeployModal`, 
as the test responsibility is on the util itself, rather than the rpc api
=> refactor: add `verifyIfAccountNeedUpgradeOrDeploy` method to group the account deploy or upgrade required validation logic

packages/starknet-snap/package.json
This PR is to decrease the test coverage limit of mocha from 70 to 50, to avoid the coverage error when move test from mocha to jest
=> refactor: decrease test coverage limit

packages/starknet-snap/package.json, packages/starknet-snap/src/index.ts, packages/starknet-snap/src/utils/lock.test.ts, packages/starknet-snap/src/utils/lock.ts, packages/starknet-snap/src/utils/snap-state.test.ts, packages/starknet-snap/src/utils/snap-state.ts, yarn.lock
This PR is to add state management base class `SnapStateManager`
it provides the functionally of `update, get, set, withTransaction, commit, rollback`
- `get` and `set` is the simple method to get the state and set the state.
- `update` is an method combine with get, then set, but also compatible with transaction mode.
- `withTransaction` is a method to init a transaction by getting the state, and do the callback, if anything happen, it will rollback to the state that we get previously, it can combine with`update` to use.
- `commit` is a method to force commit in a transaction before it auto commit.
- `rollback` is a internal method to rollback the state.
example use:
```typescript
export type SnapState = {
walletIds: string[];
wallets: Wallets;
};
class MyState extends …
```
=> chore: add state management base class and shared lock

packages/starknet-snap/src/utils/rpc.test.ts, packages/starknet-snap/src/utils/rpc.ts
This PR is to add a sharable rpc handler to have some share workflow across different rpc method.
`RpcController` is an abstract class provide the basic need of an RPC handler, 
- when extends this class, it will apply the workflow of request & response validation by using the internal method `preExecute` and `postExecute`. 
- Which also provide the extensibility to override those workflow if needed
`AccountRpcController` is another abstract class to expends `RpcController`
- it apply the workflow of getting account from the address
=> chore: add sharable rpc handler 

packages/starknet-snap/src/state/account-state-manager.test.ts, packages/starknet-snap/src/state/account-state-manager.ts, packages/starknet-snap/src/state/filter.ts, packages/starknet-snap/src/state/state-manager.ts, packages/starknet-snap/src/utils/index.ts
This PR is to add `AccountStateManager` to manage the account data in state
This PR also create an Filter Class to allow us to have data filter in OOP
usage:
```typescript
class MyFilter
extends Filter<string, AccAcontract> {
protected _apply(data: AccAcontract): boolean {
return (
data.address === this.search
);
}
}
const mgr = new AccountStateManager()
const result = await mgr.list([
new MyFilter("address")
])
```
=> refactor: add `AccountStateManager`

packages/starknet-snap/src/state/__tests__/helper.ts, packages/starknet-snap/src/state/account-state-manager.test.ts, packages/starknet-snap/src/state/account-state-manager.ts, packages/starknet-snap/src/state/filter.ts, packages/starknet-snap/src/state/network-state-manager.test.ts, packages/starknet-snap/src/state/network-state-manager.ts, packages/starknet-snap/src/state/state-manager.ts
This PR is to add `NetworkStateManager` as similar as this https://github.com/Consensys/starknet-snap/pull/323
this manager allow caller to:
- update, list, get the network
- set, get the current network
- add default networks by given a list of network to check if it has to update / insert
this PR also adding a test helper  in './state/__tests__/helper.ts' to reduce the duplication of the test code across all state manager
=> refactor: add `NetworkStateManager`

packages/starknet-snap/src/state/token-state-manager.test.ts, packages/starknet-snap/src/state/token-state-manager.ts
This PR is to add `TokenStateManager` to manage the token state as similar as this https://github.com/Consensys/starknet-snap/pull/323
this manager allow caller to:
- update, list, get the token
- get eth token by chain id
- get strj token by chain id
- add default tokens by given a list of tokens to check if it has to update / insert
=> refactor: add `TokenStateManager` 

packages/starknet-snap/src/state/transaction-state-manager.test.ts, packages/starknet-snap/src/state/transaction-state-manager.ts, packages/starknet-snap/src/types/snapState.ts, packages/starknet-snap/test/utils.ts
This PR is to add TransactionStateManager to manage the txn state as similar as this https://github.com/Consensys/starknet-snap/pull/323
this manager allow caller to:
- update, add , get the txn
- list the txns by different search conditions, by `[Txn Type, Execution Status, Finality Status, Timestamp, Contract Address, Send Address, Chain Id, Txn Hash ]`
- remove the txns by the same search conditions as above
=> refactor: add `TransactionStateManager`

packages/starknet-snap/src/__tests__/helper.ts, packages/starknet-snap/src/index.test.ts, packages/starknet-snap/src/rpcs/__tests__/helper.ts, packages/starknet-snap/src/state/__tests__/helper.ts, packages/starknet-snap/src/state/account-state-manager.test.ts, packages/starknet-snap/src/state/account-state-manager.ts, packages/starknet-snap/src/state/network-state-manager.test.ts, packages/starknet-snap/src/state/network-state-manager.ts, packages/starknet-snap/src/state/token-state-manager.test.ts, packages/starknet-snap/src/state/token-state-manager.ts, packages/starknet-snap/src/state/transaction-state-manager.test.ts, packages/starknet-snap/src/utils/rpc.test.ts, packages/starknet-snap/src/utils/snapUtils.test.ts, packages/starknet-snap/test/snap-provider.mock.ts
This PR is to fix the comments on
> maybe we call this getTransaction, as it is very different from findTransactions above. Having similar name could be confusing.
> yup, so lets change all in other state manager too in other PR
_Originally posted by @khanti42 in https://github.com/Consensys/starknet-snap/pull/328#discussion_r1724820935_
and
move the test helper from
`./test/utils.ts`
to
`./src/__tests__/helper.ts`
and
add new **testing util method** `generateRandomValue` to generate a security-sensitive random value that recommended by sonarcloud.
=> chore: maintain the naming convention for get single entity in all state manager

packages/starknet-snap/src/utils/superstruct.test.ts, packages/starknet-snap/src/utils/superstruct.ts
This PR introduces the `createStructWithAdditionalProperties` utility function that allows to combine a predefined set of properties with dynamically added properties, enabling more granular control over type validation without requiring full validation upfront. Its designed to facilitate the validation of complex StarkNet types in a flexible and iterative manner.
Example :
```
const predefined = object({
name: string(),
age: number(),
});
const MyStruct = createStructWithAdditionalProperties(predefined);
const data = {
name: 'John',
age: 30,
nickname: 'Johnny', // This will be validated as `any` since `additionalPropertyTypes` defaults to `any`.
};
const [error, result] = MyStruct.validate(data);
if (error) {
console.error(error);
} else {
console.log(result); // { name: 'John', age: 30, …
```
=> feat: Addition of `createStructWithAdditionalProperties` for Incremental Validation of Complex StarkNet Types

packages/starknet-snap/src/index.ts, packages/starknet-snap/src/rpcs/executeTxn.ts, packages/starknet-snap/src/rpcs/sign-declare-transaction.ts, packages/starknet-snap/src/rpcs/signMessage.ts, packages/starknet-snap/src/rpcs/signTransaction.ts, packages/starknet-snap/src/utils/formatterUtils.test.ts, packages/starknet-snap/src/utils/formatterUtils.ts
**Backward Compatibility for Request Parameters**
This PR ensures backward compatibility with version 2.9.0 for StarkNet-related methods (`starknet_sign*`, `starknet_execute`, and `starknet_declare`). 
- **`signerAddress` to `address` mapping**: In older versions, `starknet_sign*` methods used the `signerAddress` field. This update ensures that if `signerAddress` is passed in the request, it is mapped to the `address` field required by the new version.
- **`senderAddress` to `address` mapping**: Similarly, for `starknet_execute` and `starknet_declare`, which previously used `senderAddress`, the PR adds logic to map this to `address`.
By handling both `signerAddress` and `senderAddress`, this update allows for smooth transitions to the new parameter structure without breaking existing …
=> chore: ensure backward compatibility with remoteEntry.js of snap v2.9.0

packages/starknet-snap/src/index.ts
As in current implementation, logger is only initialised when a request send from dapp
When the home screen open without connect to a dapp, it will display an error due to logger is not initialised
This PR is to move the initialised part into `index.ts` to have single initialisation for all
=> fix: snap homepage screen error if the logger is not initialised 

packages/get-starknet/src/wallet.ts
this PR is to fix the address not update when network change
it is due to an user may have 2 different address when using different network due to different cairo contract version / contract upgrade
=> fix(get-starknet): address not update when network change

packages/starknet-snap/src/config.ts, packages/starknet-snap/src/state/network-state-manager.test.ts, packages/starknet-snap/src/state/network-state-manager.ts, packages/starknet-snap/src/utils/snapUtils.ts
This PR is to update the `getNetwork` , `updateNetwork` & `getCurrentNetwork` logic in `NetworkStateManager`
it changes:
`getNetwork` -> look up configuration -> available network 
`updateNetwork` -> as  `getNetwork` update with fallback look up, the update method has to update the state, so it search the entity by using the underlying `find` instead
`getCurrentNetwork` -> return configuration default network
=> refactor(NetworkStateManager): update `NetworkStateManager` with new configuration

packages/starknet-snap/src/utils/snap-state.ts
This PR is to change `StateManager` to return value in `withTransaction`
in any case if the withTransaction execute a callback and if there is a returned value in callback
the value should be returned to caller
=> refactor(StateManager): change `StateManager` to return value in `withTransaction`

packages/starknet-snap/src/index.ts, packages/starknet-snap/src/rpcs/displayPrivateKey.test.ts, packages/starknet-snap/src/rpcs/displayPrivateKey.ts, packages/starknet-snap/src/rpcs/estimateFee.test.ts, packages/starknet-snap/src/rpcs/executeTxn.test.ts, packages/starknet-snap/src/rpcs/executeTxn.ts, packages/starknet-snap/src/rpcs/sign-declare-transaction.test.ts, packages/starknet-snap/src/rpcs/sign-declare-transaction.ts, packages/starknet-snap/src/rpcs/signMessage.test.ts, packages/starknet-snap/src/rpcs/signMessage.ts, packages/starknet-snap/src/rpcs/signTransaction.test.ts, packages/starknet-snap/src/rpcs/signTransaction.ts, packages/starknet-snap/src/rpcs/verify-signature.test.ts, packages/starknet-snap/src/utils/error.test.ts, packages/starknet-snap/src/utils/error.ts, packages/starknet-snap/src/utils/exceptions.ts, packages/starknet-snap/src/utils/rpc.test.ts, packages/starknet-snap/src/utils/rpc.ts
This PR is to add an error wrapper to integrate the error code from 'get-starknet' wallet rpc error
To avoid breaking any existing error format/type
we extends the current snap error and create a error wrapper `walletRpcError` by using the `data` field from the `SnapError` Constructor 
Example of an error object return to the Snap Consumer
```typescript
{
"code": 4001,
"message": "User rejected the request.",
"data": {
// Error wrapper
"walletRpcError": {
// 'get-starknet' wallet rpc error code
"code": 113
}
}
}
```
for now we have implement above format into 
- UserRejectedOpError // Error that extends UserRejectedRequestError
- InvalidRequestParamsError // Error that extends InvalidParamsError
- UnknownError // Error that extends SnapError
- InvalidNetworkError // when network switch to …
=> chore(Error): add error wrapper for wallet rpc error code

packages/starknet-snap/src/__tests__/fixture/callsExamples.json, packages/starknet-snap/src/rpcs/executeTxn.test.ts, packages/starknet-snap/src/rpcs/executeTxn.ts
This PR addresses the following changes:
1. **Fixture Update:**
- The `callsExamples.json` fixture has been updated to handle both cases where `calls` can be either an array or a single object. This ensures that the test scenarios are consistent with the real-world behavior where `calls` might be in different formats.
Changes:
- Previously, `calls` were always treated as an array. The second example in the fixture now provides `calls` as a single object, allowing the tests to cover this scenario.
2. **Test Enhancements:**
- Refactored the `executeTxn.test.ts` tests to use `it.each` to handle both cases where `calls` could be either an array or a single object.
- This approach simplifies the test by parameterizing both cases (`Call[]` and `Call`), ensuring that the code is properly tested …
=> fix: RPC `starkNet_executeTxn` storing in-correct state data if  the params `calls`  is not an array

packages/get-starknet/src/__tests__/helper.ts, packages/get-starknet/src/utils/rpc.ts, packages/get-starknet/src/wallet.test.ts, packages/get-starknet/src/wallet.ts
This PR is to change the `MetaMaskSnapWallet` lock handling on `init` method
This is because, we no longer need to init with given network,
But we might have a use case that the caller of `init` already running a lock
With the update , we can allow caller to choose init with lock or not
in addtional, this PR also update the test of the MetaMaskSnapWallet to increase the coverage
=> refactor(get-starknet): change `MetaMaskSnapWallet` lock handling

packages/get-starknet/src/__tests__/helper.ts, packages/get-starknet/src/rpcs/switch-network.test.ts, packages/get-starknet/src/rpcs/switch-network.ts, packages/get-starknet/src/utils/rpc.ts, packages/get-starknet/src/wallet.test.ts, packages/get-starknet/src/wallet.ts
This PR is adding `wallet_switchStarknetChain` into get-starknet
wallet_switchStarknetChain will override the parent execute , as it has to ensure the it will only execute once at a time from the dapp
Requires this PR to be merged first:
=> feat(get-starknet): add `wallet_switchStarknetChain` rpc method

packages/starknet-snap/src/index.ts, packages/starknet-snap/src/rpcs/get-deployment-data.test.ts, packages/starknet-snap/src/rpcs/get-deployment-data.ts, packages/starknet-snap/src/rpcs/index.ts, packages/starknet-snap/src/utils/exceptions.ts
This PR is to add RPC `starkNet_getDeploymentData` into the snap
as it is designed for get-starknet v4
The purpose to have this API is to
- having the checking to the account, where it should deployed / upgrade, and enforce the user to deployed / upgrade in our dapp
- does not need to depulicate the deployment data in the snap and get-starkent
=> feat: add RPC `starkNet_getDeploymentData`

packages/get-starknet/src/rpcs/get-permissions.test.ts, packages/get-starknet/src/rpcs/get-permissions.ts, packages/get-starknet/src/rpcs/supported-specs.test.ts, packages/get-starknet/src/rpcs/supported-specs.ts, packages/get-starknet/src/rpcs/supported-wallet-api.test.ts, packages/get-starknet/src/rpcs/supported-wallet-api.ts, packages/get-starknet/src/wallet.ts
This PR is to remove the snap connection on rpcs that return static information
as they dont necessary to connect to the snap
APIs include:
- wallet_supportedWalletApi
- wallet_supportedSpecs
- wallet_getPermissions
=> refactor(get-starknet): remove the snap connection on rpcs that return static information

packages/get-starknet/src/rpcs/deployment-data.ts, packages/get-starknet/src/rpcs/sign-typed-data.test.ts, packages/get-starknet/src/rpcs/sign-typed-data.ts, packages/get-starknet/src/rpcs/watch-asset.ts
this PR is to fix the incorrect params in `wallet_signTypedData` when calling the snap API
- it was using chain id as the address
- but it should use the address
=> fix(get starknet): fix incorrect params in RPC `wallet_signTypedData`

packages/get-starknet/src/accounts.ts, packages/get-starknet/src/rpcs/add-declare.test.ts, packages/get-starknet/src/rpcs/add-declare.ts, packages/get-starknet/src/rpcs/add-invoke.test.ts, packages/get-starknet/src/rpcs/add-invoke.ts, packages/get-starknet/src/rpcs/deployment-data.ts, packages/get-starknet/src/rpcs/sign-typed-data.test.ts, packages/get-starknet/src/rpcs/sign-typed-data.ts, packages/get-starknet/src/rpcs/watch-asset.test.ts, packages/get-starknet/src/rpcs/watch-asset.ts, packages/get-starknet/src/signer.ts, packages/get-starknet/src/snap.ts
This PR is to change the get starknet snap params structure from arguments in array to arguments in object
it is because it will more easy to read and config with default value
And reduce the get current network call from the new get-starknet PRC
- it was called everytime when submit a request to snap
- it will only called if the chain id is undefined 
Below PRs required to be merged before hand:
=> refactor(get-starknet): change get starknet snap params structure

packages/starknet-snap/src/index.ts
This PR is to fix the incorrect params passed to SNAP RPCs :
- starkNet_signDeclareTransaction
- starkNet_verifySignedMessage
- starkNet_declareContract
- starkNet_getDeploymentData
fix: Fix incorrect params passed to RPCs `starkNet_signDeclareTransaction`, `starkNet_verifySignedMessage`, `starkNet_declareContract` and `starkNet_getDeploymentData`
=> fix(SNAP): fix incorrect params passed to SNAP RPCs

packages/get-starknet/src/wallet.test.ts, packages/get-starknet/src/wallet.ts, packages/starknet-snap/src/index.ts
This PR is to fix the on/off event. The signature is updated to match interface. And the throw is removed to allow the use of WalletAccount as per the starknet documentation: http://starknetjs.com/docs/next/guides/walletAccount#select-a-wallet. If we through the WalletAccount object can't be created.
=> chore(get-starknet): remove `Method not supported` exception for "`on` " and "`off`" event handlers

packages/starknet-snap/src/config.ts, packages/starknet-snap/src/utils/explorer.test.ts, packages/starknet-snap/src/utils/explorer.ts, packages/starknet-snap/src/utils/index.ts, packages/starknet-snap/src/utils/snap-ui.ts, packages/starknet-snap/src/utils/string.test.ts, packages/starknet-snap/src/utils/string.ts
This PR is to adding some utils method to manage the SNAP UI in a centralise file
to be more convenient when we need to replace with JSX component later
it create some reusable method to generate UI
- rowUI : is to create a row component with text field
- addressUI: is to create a row component with address and linked with explorer
- networkUI: is to create a row component with default label `Network`
- headerUI: is to create a heading component
- dividerUI: is to create a divider component
- signerUI: is to create a addressUI with default label `Signer Address`
- jsonDataUI: is to create a row component with Json Serializer
=> refactor(SNAP): add utils to manage snap ui

packages/wallet-ui/src/services/useStarkNetSnap.ts
This PR is to ensure snapId name compatibility between get-starknet and wallet-ui. 
In get-starknet the snapId is set with an env variable. However ending / are removed when loaded with `process.env` hence the snapId does not match the one in wallet-ui. We remove the ending / in wallet-ui to ensure compatibility between the two.
chore: remove ending slash on localSnapId
=> chore(wallet-ui): remove ending slash on localSnapId 

packages/starknet-snap/src/__tests__/helper.ts, packages/starknet-snap/src/state/__tests__/helper.ts, packages/starknet-snap/src/state/request-state-manager.test.ts, packages/starknet-snap/src/state/request-state-manager.ts, packages/starknet-snap/src/state/state-manager.ts, packages/starknet-snap/src/types/snapState.ts
This PR is to add transaction request state manager to prepare the task when using interactive UI for token unit selection when process execute transaction
=> chore: add transaction request state manager

.github/workflows/deploy.yml, packages/get-starknet/src/wallet.ts, packages/get-starknet/webpack.config.build.js
Version enforcement is now handled globally using `process.env.SNAP_VERSION`. 
Retained the `_snapVersion` parameter in the MetaMaskSnapWallet constructor for backward compatibility, as some existing consumers explicitly pass it.
=> chore: set get-starknet Snap's version through env variable

packages/starknet-snap/src/__tests__/helper.ts, packages/starknet-snap/src/ui/controllers/user-input-event-controller.test.ts, packages/starknet-snap/src/ui/controllers/user-input-event-controller.ts
This PR is to update the test in  `UserInputEventController`
and it also fixing  the bug in generate `errorMessage`
- it was using the selectedFeeToken from the updated request, but the request may change, it was passed because the test is not correct
- it using the selectedFeeToken from the original request, and adding a test to make sure both token not same
=> chore: update test for `UserInputEventController`

packages/starknet-snap/src/rpcs/abstract/chain-rpc-controller.test.ts, packages/starknet-snap/src/rpcs/abstract/chain-rpc-controller.ts, packages/starknet-snap/src/state/__tests__/helper.ts
This PR is to add `ChainRpcController` for the case that a RPC doesnt need account discover, but just getting the network instance by a chainId 
the `ChainRpcController` will place into './rpcs/abstract'
due to stateManager is included  `ChainRpcController`, it will result a cycle require when some RPC extends the ChainRpcController
and the other abstract RPC controllers should move to the same place
=> chore: add base controller `ChainRpcController`

packages/get-starknet/webpack.config.build.js
This PR introduces cache-busting query parameters to Webpack’s filename and chunkFilename configurations. This change ensures that both entry point files and dynamically imported chunks avoid issues caused by DNS or browser caching, particularly in production environments. The addition of query parameters (?v=[fullhash]) helps load the latest versions of assets, even if stale files are cached.
=> chore: Add Cache-Busting Query Parameters to Webpack Output Files

packages/starknet-snap/src/index.test.tsx, packages/starknet-snap/src/index.tsx, packages/starknet-snap/src/utils/permission.test.ts, packages/starknet-snap/src/utils/permission.ts
This PR is to add permission boundary to limit the access of some RPC API by different origins ([reference](https://consensyssoftware.atlassian.net/jira/software/projects/SF/boards/472?selectedIssue=SF-738))
It also include:
- due to no use case exist, we removed the access for RPCs - `starkNet_addNetwork`, `starkNet_estimateAccountDeployFee` and `starkNet_getStoredTransactions`
feat: Add permission boundary.  Block RPCs - `starkNet_addNetwork`, `starkNet_estimateAccountDeployFee` and `starkNet_getStoredTransactions` access for any origin (#448)
=> feat: add permission boundary

packages/starknet-snap/openrpc/starknet_snap_api_openrpc.json, packages/starknet-snap/src/index.tsx, packages/starknet-snap/src/rpcs/get-addr-from-starkname.test.ts, packages/starknet-snap/src/rpcs/get-addr-from-starkname.ts, packages/starknet-snap/src/rpcs/index.ts, packages/starknet-snap/src/utils/permission.test.ts, packages/starknet-snap/src/utils/permission.ts, packages/starknet-snap/src/utils/starknetUtils.test.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/src/utils/superstruct.ts, packages/wallet-ui/src/components/ui/molecule/AddressInput/AddressInput.style.ts, packages/wallet-ui/src/components/ui/molecule/AddressInput/AddressInput.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx, packages/wallet-ui/src/services/useStarkNetSnap.ts, packages/wallet-ui/src/utils/utils.ts
This PR adds support to sending money to a .stark domain.
Close https://github.com/Consensys/starknet-snap/issues/185
=> feat: allow users to transfer money to a .stark name (#437)

.github/workflows/deploy.yml, .github/workflows/publish-npm.yml
This PR to replace VOYAGER API KEY secrets to DIN API KEY secrets in the CICD pipeline
=> chore: replace secrets ` ALCHEMY_API_KEY` to `DIN_API_KEY` in CICD pipeline

packages/starknet-snap/src/utils/permission.ts
This PR is to fix permission boundary to include RPC method 'ping'
=> chore: fix permission boundary

packages/starknet-snap/src/__tests__/helper.ts, packages/starknet-snap/src/rpcs/__tests__/helper.ts, packages/starknet-snap/src/rpcs/estimate-fee.test.ts, packages/starknet-snap/src/rpcs/execute-txn.test.ts, packages/starknet-snap/src/rpcs/execute-txn.ts, packages/starknet-snap/src/state/request-state-manager.ts, packages/starknet-snap/src/types/snapState.ts, packages/starknet-snap/src/ui/controllers/user-input-event-controller.test.ts, packages/starknet-snap/src/ui/controllers/user-input-event-controller.ts, packages/starknet-snap/src/utils/__tests__/helper.ts, packages/starknet-snap/src/utils/fee.test.ts, packages/starknet-snap/src/utils/fee.ts, packages/starknet-snap/src/utils/starknetUtils.test.ts, packages/starknet-snap/src/utils/starknetUtils.ts
This PR is to fix `ResourceBounds` that has not sum after estimate the fees
it include:
- add  helper class `ConsolidateFees`  
- sum resourceBounds with `ConsolidateFees`  
- re-work test to simplify mock estimate fees
=> fix: consolidate `ResourceBounds` sum

packages/wallet-ui/src/services/useStarkNetSnap.ts, packages/wallet-ui/src/utils/constants.ts, packages/wallet-ui/src/utils/utils.ts
Mute the error message if user denied the operation of : 
- starkNet_executeTxn
- starkNet_addErc20Token
- starkNet_upgradeAccContract
- starkNet_createAccountLegacy
- starkNet_displayPrivateKey
fix: Mute Wallet UI error message when user deny a request (#460)
=> fix: mute wallet ui error message on rejected request

packages/starknet-snap/src/__tests__/helper.ts, packages/starknet-snap/src/state/transaction-state-manager.test.ts, packages/starknet-snap/src/ui/utils.test.tsx, packages/starknet-snap/src/upgradeAccContract.ts, packages/starknet-snap/src/utils/formatter-utils.test.ts, packages/starknet-snap/src/utils/formatter-utils.ts, packages/starknet-snap/src/utils/snapUtils.ts, packages/starknet-snap/src/utils/starknetUtils.ts, packages/starknet-snap/src/utils/superstruct.test.ts
This PR is to refine the SNAP for StarkScan migration
it includes:
- update hardcode value `transfer` and `upgrade` to enum ContractFuncName ,
=> chore: refine SNAP for StarkScan migration

packages/starknet-snap/src/utils/factory.test.ts, packages/starknet-snap/src/utils/factory.ts, packages/starknet-snap/src/wallet/account/contract.ts, packages/starknet-snap/src/wallet/account/index.ts, packages/starknet-snap/src/wallet/account/service.test.ts, packages/starknet-snap/src/wallet/account/service.ts
This PR is to add a factory method to create `AccountService` 
This PR also include a change on how to construct a  `AccountService`  and add  get deploy payload method in `CairoAccountContract`
=> feat: add account service factory

packages/starknet-snap/src/rpcs/get-current-account.test.ts, packages/starknet-snap/src/rpcs/get-current-account.ts
This change is to enable RPC `starkNet_getCurrentAccount` to return the account data from state or derive it directly
- add a boolean optional params `fromState` to configurate the RPC `starkNet_getCurrentAccount` to return data from state or derive it from account service
- if the state does not contains a data, it will fall back to use account service to derive a default current account
=> feat: update RPC `starkNet_getCurrentAccount` to return the account from state

packages/wallet-ui/src/components/ui/molecule/AccountSwitchModal/AccountSwitchModal.view.tsx, packages/wallet-ui/src/services/useStarkNetSnap.ts
This PR is to fix the incorrect switch account RPC endpoint in Wallet-UI
- Update switch account RPC endpoint to `starkNet_switchAccount `
- Remove duplicate `initWalletData` when adding a new account
- Disable  `InfoModal` temporarily
=> fix: incorrect switch account RPC endpoint in Wallet-UI

packages/starknet-snap/src/config.ts, packages/starknet-snap/src/state/__tests__/helper.ts, packages/starknet-snap/src/state/account-state-manager.test.ts, packages/starknet-snap/src/state/account-state-manager.ts, packages/starknet-snap/src/utils/exceptions.ts, packages/starknet-snap/src/wallet/account/service.test.ts, packages/starknet-snap/src/wallet/account/service.ts
This PR is to remove the blocking of account create limit
- remove related test case for account create limit
- remove account limit verification in account service
- remove dead code and config for account create limit
=> chore: unblock account create limit

docs/tutorial-resolving-stuck-funds.md
This PR is to update the tutorial on funds recovery to match the new version of the staging environment that will be deployed to manage both funds recovery on non-deployed Cairo 0 and non-deployed Cairo 1.
=> chore: update docs for funds recovery

packages/wallet-ui/src/App.tsx, packages/wallet-ui/src/components/pages/Home/Home.view.tsx, packages/wallet-ui/src/components/ui/molecule/AccountSwitchModal/AccountSwitchModal.stories.tsx, packages/wallet-ui/src/components/ui/molecule/AccountSwitchModal/AccountSwitchModal.style.ts, packages/wallet-ui/src/components/ui/molecule/AccountSwitchModal/AccountSwitchModal.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionsList.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.stories.tsx, packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.view.tsx, packages/wallet-ui/src/components/ui/organism/AddTokenModal/AddTokenModal.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.stories.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx, packages/wallet-ui/src/slices/walletSlice.ts, packages/wallet-ui/src/types/index.ts
This PR adds the support of infinite account to Wallet-UI 
Changes : 
- The "My Account" is replaced by "Account X" where is X is the account number (accountIndex + 1) 
- The list of accounts now uses the Account Icon and Account name and short address for better UI/UX
- When the account number is higher than 3 a scrollbar appears 
See the video below : 
https://github.com/user-attachments/assets/dfcfe21b-4197-4510-91b3-c21fdcc925d3
=> feat: wallet-ui multiple accounts scrollbar

packages/wallet-ui/src/App.tsx, packages/wallet-ui/src/components/pages/Home/Home.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionsList.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountSwitchModal/AccountSwitchModal.view.tsx, packages/wallet-ui/src/components/ui/organism/AddTokenModal/AddTokenModal.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx, packages/wallet-ui/src/slices/walletSlice.ts
This PR is to remove the many use of DUMMY_ADDRESS throughout the code base by using a dummy account at the redux state level.
=> chore: currentAccount is always defined in walletSlice redux state

packages/starknet-snap/src/config.ts, packages/starknet-snap/src/rpcs/add-account.test.ts, packages/starknet-snap/src/rpcs/add-account.ts, packages/starknet-snap/src/rpcs/get-current-account.test.ts, packages/starknet-snap/src/rpcs/switch-account.test.ts, packages/starknet-snap/src/rpcs/switch-account.ts, packages/starknet-snap/src/state/__tests__/helper.ts, packages/starknet-snap/src/state/account-state-manager.test.ts, packages/starknet-snap/src/state/account-state-manager.ts, packages/starknet-snap/src/utils/exceptions.ts, packages/starknet-snap/src/wallet/account/service.test.ts, packages/starknet-snap/src/wallet/account/service.ts
This PR is to refine the account service and fix some edge case bug
- It will be not longer auto update the account state from `deriveAccountByIndex`, instead the update process split into the workflow that using this method:
- Update the account state after derive account by address to make sure it sync the data
- Add the account to state when adding a new account
- Add the account to state when get the current account if the current account not yet set
- Add validation to make sure the state can only store 1 address per account index 
- remove `upsertAccount` from AccountStateManager to replace by more specific purpose method -`updateAccountByAddress`,`addAccount`
=> chore: refine account service

packages/wallet-ui/src/assets/locales/en.json, packages/wallet-ui/src/assets/locales/fr.json, packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.style.ts, packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountSwitchModal/AddAccountModal/AddAccountModal.style.ts, packages/wallet-ui/src/components/ui/organism/AccountSwitchModal/AddAccountModal/AddAccountModal.view.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.style.ts, packages/wallet-ui/src/services/useSnap.ts, packages/wallet-ui/src/services/useStarkNetSnap.ts, packages/wallet-ui/src/utils/constants.ts, packages/wallet-ui/src/utils/utils.ts
This PR is to refine the name management UI
- Rename `setAccountName` to `updateAccountName` to align the naming convention  
- Add error message for the add account, update account name workflow
- Add Constants to store the account name length requirement
- When add new account, if the name is not given, convert to undefined and let the SNAP to assign a default name
=> chore: refine account name management UI

packages/wallet-ui/src/App.tsx, packages/wallet-ui/src/components/pages/Home/Home.view.tsx, packages/wallet-ui/src/components/ui/molecule/AssetsList/AssetsList.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionListItem/TransactionListItem.view.tsx, packages/wallet-ui/src/components/ui/molecule/TransactionsList/TransactionsList.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountSwitchModal/AccountSwitchModal.view.tsx, packages/wallet-ui/src/components/ui/organism/AddTokenModal/AddTokenModal.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/Header.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx, packages/wallet-ui/src/components/ui/organism/SideBar/SideBar.view.tsx, packages/wallet-ui/src/services/useMultiLanguage.ts, packages/wallet-ui/src/services/useSnap.ts, packages/wallet-ui/src/services/useStarkNetSnap.ts
This PR is to fix the redux state on UI components to only subscribe the state that it needed, 
to avoid updating a state and cause all component re-render
e.g 
- at T1 Component A subscribes the wallet state, however it only use 1 of the props - 'xx' from the wallet state;
```
const wallet = useAppSelector((state) => state.wallet)
const varToUse = wallet.xx
```
- at T2, we update a props - 'yy' on wallet
- at T3, Component A will be re-render, which not expected
- change `useAppSelector((state) => state.wallet)` to `useAppSelector((state) => state.wallet.{xxxxx}` to only subscribe the state that it needed
=> fix: enhance performance by muting unnecessary state subscription in UI

packages/get-starknet/package.json, packages/get-starknet/src/snap.test.ts, packages/get-starknet/src/snap.ts, packages/get-starknet/src/type.ts, yarn.lock
This PR is to add a fix for a case that the SNAP does not auto update if the version is outdate in get-starknet
if the SNAP version is outdate , the  get-starknet request workflow will trigger a reconnect workflow to update the SNAP
Changes:
- Add the logic to detect the SNAP version is outdate or not, and trigger re-install
=> fix: the SNAP does not auto update if the version is outdate in get-starknet

packages/wallet-ui/src/components/ui/organism/AccountDetailsModal/AccountDetailsModal.view.tsx
This PR is to fix the edge case on wallet UI, 
While edit the name from account detail, but the name is undefined due to previous snap was installed
there will be a JS error caused by accountName.trim()
=> chore(wallet-ui): fix edge case when account name is undefined in `AccountDetailsModal`

packages/wallet-ui/src/components/ui/organism/AccountListModal/AccountItem.view.tsx, packages/wallet-ui/src/components/ui/organism/AccountListModal/AccountList.view.tsx, packages/wallet-ui/src/hooks/index.ts, packages/wallet-ui/src/hooks/useAccountVisibility.ts
This PR is to hide the `HiddenAccount` button if there is only 1 visible account
- Add `showIconButton` flag on `AccountItem` to indicate if the  `HiddenAccount` button visible or not
- Add `useAccountVisibility` hook to consolidate the logic for account visibility management
=> chore(wallet-ui): hide the `HiddenAccount` button if there is only 1 visible account

packages/wallet-ui/src/assets/locales/en.json, packages/wallet-ui/src/assets/locales/fr.json, packages/wallet-ui/src/components/ui/organism/AccountListModal/AccountItem.style.ts, packages/wallet-ui/src/components/ui/organism/AccountListModal/AccountItem.view.tsx
This PR enhances the Account List Modal by introducing a contextual menu that allows users to hide/unhide accounts and copy addresses.
https://github.com/user-attachments/assets/0744e41c-5bd0-4138-acd5-61e3fe1098ae
=> feat: account list contextual menu with hide/unhide and copy address feature

packages/wallet-ui/src/services/useStarkNetSnap.ts, packages/wallet-ui/src/slices/networkSlice.ts
The PR introduces a new Redux action: `setNetworksAndActiveNetwork({ networks, activeNetwork })`
- Replaces the two separate dispatches with a single atomic update to both networks and activeNetwork.
- Ensures consistent and up-to-date state when reconnecting to the Snap.
- Avoids race conditions or unnecessary re-renders that could happen between two separate dispatches.
=> fix: account list mismatch when reconnecting Snap

packages/wallet-ui/src/services/useSnap.ts, packages/wallet-ui/src/utils/utils.ts
This PR fixes Snap installation and usage on Firefox latest MetaMask. 
```
request: {
method,
params: params ? removeUndefined(params) : params,
},
```
by this 
```
request: !params
? { method }
: { method, params: params ? removeUndefined(params) : params },
``` 
We add `JSON.parse(JSON.stringify( .... ))` before returning in the removeUndefined utility function.
=> fix: snap not working on firefox

packages/starknet-snap/src/ui/components/SignMessageUI.tsx
There is a typo we use `translate('signeMessagePrompt')` but it should be `translate('signMessagePrompt')`
signeMessagePrompt => signMessagePrompt
=> chore: fix translation wrong keys

packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendInputModal/SendInputModal.view.tsx, packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx, packages/wallet-ui/src/utils/utils.ts
This PR is to fix two things: 
- The USD toggle button was not showing the right amount in USD
- The max amount to be spend was not accounting for the feeToken in the calculation causing max amount error on validation screen
=> chore: fix max fees and usd toggle

packages/wallet-ui/src/utils/utils.ts
This PR fixes a bug where integer values like `"100"` were incorrectly truncated to `"1"` due to logic that assumed all inputs had a decimal point. The function now properly checks for the presence of a decimal and avoids applying decimal trimming logic to whole numbers. This ensures values like `"100"` or `"10"` are returned as-is, while still correctly trimming and formatting decimal values.
=> fix: incorrect truncation in getMaxDecimalsReadable
